services:
  ooga-booga-db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: ooga-booga-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Stores data outside the container to ensure persistence